### ISSUE TITLE
fonts

### ISSUE THREAD

**Issue by ahmedMubarak2024** [islamic-network/alquran-api#10]
need to know the font to use to read the quran-buck English phonetic tried several doesn't work 
and the font for quran-tajweed also that would be very helpful

**Comment by meezaan** [comment]
Salaam.

There's no font to read these. You have to parse them. See https://github.com/islamic-network/alquran-tools and https://alquran.cloud/tajweed-guide.

**Comment by ahmedMubarak2024** [comment]
i am working on android app and the buck version {ls~ama` which isn't understandable why is that 
also if i want quran version written in English phonetics is this available  like "Bismi Allāhi Ar-Raĥmāni Ar-Raĥīmi"

**Comment by meezaan** [comment]
The only transliteration is en.transliteration.

That does not use the Latin phonetics for English, but instead just writes English out in a readable way, like "Bismillaahir Rahmaanir Raheem".

See http://api.alquran.cloud/surah/1/en.transliteration, for instance.
