### ISSUE TITLE
Name of surah in the language of translation

### ISSUE THREAD

**Issue by husayt** [islamic-network/alquran-api#6]
There is no field with the name of surah in the language of chosen translation. There is a name in English, in arabic, in transliteration, but not in the language of translation.

Thank you for this amazing work. Jzkhr

**Comment by meezaan** [comment]
Al Salaamu Alaykum,

You're welcome.

The underlying data from Tanzil.net does not have translations for Surah names.

If you have translations for a particular language, I can look at adding them in.

Let me know if I can be of any further help.

**Comment by husayt** [comment]
Great.  I will do that.
Thank you
ASR

**Comment by meezaan** [comment]
Look forward to it :)
