### ISSUE TITLE
return audio file urls using https when request to api is made with https

### ISSUE THREAD

**Issue by tuqire** [islamic-network/alquran-api#7]
making a request to `https://api.alquran.cloud/surah/114/ar.alafasy` should return audio file urls like `https://islamcdn.com/quran/media/audio/ayah/ar.alafasy/6226` and not `http://islamcdn.com/quran/media/audio/ayah/ar.alafasy/6226`

**Comment by meezaan** [comment]
Done. http://api.alquran.cloud/ayah/245/ar.alafasy contains the http cdn url and https://api.alquran.cloud/ayah/245/ar.alafasy contains https.
