### ISSUE TITLE
Audio quran

### ISSUE THREAD

**Issue by Amel-Fathalla** [islamic-network/alquran-api#8]
Salam alaykoum u use api for mobile application
how can i get audio from api please ?
because in json array i have this
{"code":200,"status":"OK","data":[{"identifier":"fr.hamidullah","language":"fr","name":"Hamidullah","englishName":"Muhammad Hamidullah","format":"text","type":"translation"},{"identifier":"fr.leclerc","language":"fr","name":"Youssouf Leclerc","englishName":"Youssouf Leclerc","format":"audio","type":"versebyverse"}]}

My code:
var SurahInfo = {
	name: "Name of surah",
	qari_name: "name of qari"

};

const url = "what are à true url or steps to get audio ";

audio.initPlayer("url", surahInfo); 

//To play audio clip
audio.play();
Jazakoum Allah

**Comment by meezaan** [comment]
Salaam. Sorry I have just seen this.

A list of all audio versions: http://api.alquran.cloud/edition/format/audio

To get a particular surah for an audio version by ayah: http://api.alquran.cloud/surah/96/ar.alafasy (this response will contain an audio link which you can use to play audio)

Hope this helps.

**Comment by Oum-Abdilleh** [comment]
salam it's dont work i have error undefine

**Comment by meezaan** [comment]
What do you have an error for? What URL?

**Comment by electro199** [comment]
> To get a particular surah for an audio version by ayah: http://api.alquran.cloud/surah/96/ar.alafasy (this response will contain an audio link which you can use to play audio)

Can you please share in the doc  where it shows more clearly about which parameter to use for which ayah and surah

**Comment by meezaan** [comment]
[http://api.alquran.cloud/v1/ayah/96:1/ar.alafasy](http://api.alquran.cloud/v1/ayah/96:1/ar.alafasy)  should do what you are after.

**Comment by rashnk** [comment]
http://[api.alquran.cloud/v1/quran/ar.alafasy](http://api.alquran.cloud/v1/quran/ar.alafasy) it is working

http://[api.alquran.cloud/v1/quran/ar.abdulbasitmurattal](http://api.alquran.cloud/v1/quran/ar.abdulbasitmurattal) not working


no audio is returned for any reciters other than ar.alafasy

**Comment by meezaan** [comment]
> http://[api.alquran.cloud/v1/quran/ar.alafasy](http://api.alquran.cloud/v1/quran/ar.alafasy) it is working
> 
> http://[api.alquran.cloud/v1/quran/ar.abdulbasitmurattal](http://api.alquran.cloud/v1/quran/ar.abdulbasitmurattal) not working
> 
> no audio is returned for any reciters other than ar.alafasy

What do you mean by no audio is returned? That endpoint returns JSON which provides links to the audio files for a particular reciter.

**Comment by rashnk** [comment]
This is how I am seeing, some endpoints not returning result.
https://github.com/islamic-network/api.alquran.cloud/assets/12730428/e41ae4ff-9bec-4c1e-a984-b9c0c359879a

**Comment by meezaan** [comment]
I cannot reproduce the same issue.

Can you please share the output of a curl -iv to any of those URLs?

On the machine or network from which you are querying, are you running any anti virus or any other firewall software? This is the main reason why your connection would get closed, your firewall does not like what is coming through. This is has been the main reason for this issue in the past - a couple of other people sent emails about it and turning off the firewall and anti virus solved the problem for them.

**Comment by rashnk** [comment]
![image](https://github.com/islamic-network/api.alquran.cloud/assets/12730428/c645e44d-d5d7-44fc-b8cb-a65246b15c3d)

**Comment by rashnk** [comment]
Now it is working in the browser too, however I haven't changed anything.
![image](https://github.com/islamic-network/api.alquran.cloud/assets/12730428/5806c7a3-c7d2-4444-a6e7-2b875351e035)

**Comment by meezaan** [comment]
Also always try and use https. Also I've only seen this reported on Windows machines - so it's possible that Windows Defender is the culprit, although in one case Avast anti virus was causing a problem. I suspect the size of the response and the Arabic text together may cause the firewall a problem. Does this occur for you if you query a particular Surah? The size would be smaller, so it's possible the issue never manifests itself.
