### ISSUE TITLE
Search api

### ISSUE THREAD

**Issue by husayt** [islamic-network/alquran-api#9]
Thanks again for such a valuable resource. I am currently using it to build Quran Reader Web app. Hope to share soon and get feedback.

Would be also great to have search api, if this is something can be added.

JZKH

**Comment by meezaan** [comment]
Salaam.

There is a search endpoint - http://api.alquran.cloud/search/{{keyword}}/{{surah}}/{{edition or language}}. See https://alquran.cloud/api. Are you looking for something else?

**Comment by husayt** [comment]
I somehow missed it. This is exactly what I was looking for. Thanks
